name: Fix
description: File a bug report or UI convention fix here
labels: [bug]

body:
  - type: input
    id: title
    attributes:
      label: Title
      description: What is the title of your bug report?
      placeholder: Enter the title here
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Tell us what you were doing when the bug occurred
    validations:
      required: true

  - type: input
    id: App
    attributes:
      label: App
      description: What app was this bug or fix noted in?
      placeholder: ...
    validations:
      required: false
